version: '3.9'

volumes:
    mysql_mido:

services:
    bot:
        container_name: mido
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            - NODE_ENV=development
        links:
            - mysql_mido
        env_file:
            - .env
        volumes:
            - .:/app
        ports:
            - 5050:5000

    mysql_mido:
        container_name: mido-mysql
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=mido
            - MYSQL_USER=mido
            - MYSQL_PASSWORD=root
            - MYSQL_PORT=3306
        env_file:
            - .env
        volumes:
            - mysql_mido:/var/lib/mysql
        ports:
            - '3308:3306'
        restart: unless-stopped
        stdin_open: true
        command:
            ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: 5s
            retries: 10

    mysql-backup:
        image: fradelg/mysql-cron-backup
        depends_on:
            - mysql_mido
        restart: always
        volumes:
            - ./backups:/backup
        environment:
            - MYSQL_USER=mdio
            - MYSQL_PASS=root
            - MYSQL_DB=mido
            - CRON_TIME=0 0 * * *
            - MYSQL_HOST=mysql_mido
            - MYSQL_PORT=3306
            - TIMEOUT=10s
            - INIT_BACKUP=1
            - MAX_BACKUPS=7
